spring:
  application:
    name: HMS
  datasource:
    url: jdbc:postgresql://localhost:5432/hms
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8085
  servlet:
    context-path: /api/v1

security:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  issuer-id: t6w9z$C&F)J@McQfTjWnZr4u7x!A%D*G
  jwt:
    expiration:
      length: 17
      time-type: days
